### PR TITLE
Packit config update

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Add smoke test to testing farm.
- Increase version for packit propose-update and turn on other jobs.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
based on the logs, the s2i image looks to be borked

**Comment by lachmanfrantisek** [comment]
> based on the logs, the s2i image looks to be borked [the test failure]

@TomasTomecek What can we do with that? / Do we want to wait or merge anyway?

**Comment by TomasTomecek** [comment]
> > based on the logs, the s2i image looks to be borked [the test failure]
> 
> @TomasTomecek What can we do with that? / Do we want to wait or merge anyway?

if you're brave, you can dig in

otherwise I'd probably skip the test

**Comment by lachmanfrantisek** [comment]
@TomasTomecek I've skipped the tests. Is that OK, now? (The remaining pending statuses are probably from the old version of packit-service.)

**Pull request merged**
