### PR TITLE
[requirements.sh] move 'docker start' & 'oc cluster up' into test-requirements.sh

### PR DESCRIPTION
**Pull request by jpopelka**
Also

- we don't need to install all the python requirements as rpms if they are later installed with pip3/pip2.
- don't do 'oc cluster up' & 'oc new-project conu' if it's already set up

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/feXr](https://da.gd/feXr)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/WrKBx](https://da.gd/WrKBx)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/icR6](https://da.gd/icR6)__
* Comment: __See details for logs__

**Comment by jpopelka** [comment]
[test]

**Comment by jpopelka** [comment]
[test]

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/lucW](https://da.gd/lucW)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/5oQnf](https://da.gd/5oQnf)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/Q6OHv](https://da.gd/Q6OHv)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/2JNQD](https://da.gd/2JNQD)__
* Comment: __See details for logs__

**Comment by jpopelka** [comment]
Ready for review.

**Comment by rpitonak** [comment]
LGTM, let's merge

**Pull request merged**
