### PR TITLE
Fix tests, k8s deployments: utilize get_apps_api

### PR DESCRIPTION
**Pull request by TomasTomecek**

### CODE REVIEW

**Comment by jpopelka** [comment]
Whoops: `tests/integration/test_docker.py::test_container_metadata FAILED`

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/LtjS0](https://da.gd/LtjS0)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/RiJoY](https://da.gd/RiJoY)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
I can't do small pull requests -_-

I suggest going commit by commit.

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/qrshs](https://da.gd/qrshs)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
[test]

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/BJXWw](https://da.gd/BJXWw)__
* Comment: __See details for logs__

**Pull request merged**
