### PR TITLE
0.4.0 release

### PR DESCRIPTION
**Pull request by TomasTomecek**
TODO:
 * [x] https://github.com/user-cont/conu/pull/218

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/lCVJ](https://da.gd/lCVJ)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/mFsK](https://da.gd/mFsK)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: success, return code = __0__ 
* Result url: __[https://da.gd/B01Ou](https://da.gd/B01Ou)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
green! merge time?

**Comment by dhodovsk** [comment]
*Finger crossed* :)

**Pull request merged**
