### PR TITLE
vagrantfile: start docker before running tests

### PR DESCRIPTION
**Pull request by TomasTomecek**

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/ThAmo](https://da.gd/ThAmo)__
* Comment: __See details for logs__

**Comment by jpopelka** [comment]
@TomasTomecek there are some problems with the tests, please check them

**Comment by TomasTomecek** [comment]
I fixed the `test_run_with_volumes_metadata_check` test. The s2i test seems to be a flake, and the pod test is known to broken afaik.

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/HDoio](https://da.gd/HDoio)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
I reported issues on the failing tests, can we merge?

**Pull request merged**
