### PR TITLE
req.sh: clarify deps, remove make; remove pytest from dfile.tests

### PR DESCRIPTION
**Pull request by TomasTomecek**
related https://github.com/user-cont/conu/pull/290

### CODE REVIEW

**Comment by jscotka** [comment]
Thanks a lot. situation with various requiremetns is very unclear.

could be improved, for example, docker files for tests contain explicit using pip/pip3, in vagrant, there were used way with make, in make file there is just pip install . and not pip and pip3 install together
and also that situation with ``requirements.in`` and ``requirements.txt`` what is sometimes (I don't know  exactly when) updated by this ``.in`` file

**Comment by jpopelka** [comment]
How is this supposed to fix anything when enum34 is already in [requirements.txt](https://github.com/user-cont/conu/blob/master/requirements.txt#L13) ?

**Comment by TomasTomecek** [comment]
2 things:

1. ideally, req.sh would contain all the rpm deps and other logic needed to run conu (what Honza needs)
2. we prefer RPMs over upstream content from PyPI: we can easily patch RPMs, not the content on PyPI

**Comment by jpopelka** [comment]
Ok, I personally prefer not to duplicate things, other than in cases documented [here](https://github.com/user-cont/conu/blob/master/requirements.sh#L10).

But if you want it, then you're still missing `python[2|3]-six`, `python[2|3]-docker` and `python[2|3]-kubernetes`.

**Comment by TomasTomecek** [comment]
okay, that makes sense, let's fix the doc string then

**Comment by jpopelka** [comment]
And also I think that installing the rpms is quite useless since there are exact versions in requirements.txt so the `pip install` will uninstall the rpm versions and install different ones.

**Comment by TomasTomecek** [comment]
PTAL

**Pull request merged**
