### PR TITLE
add requirements to requiremets.sh file

### PR DESCRIPTION
**Pull request by jscotka**
missing requirements, found by running vagrant file

### CODE REVIEW

**Comment by jpopelka** [comment]
They are in https://github.com/user-cont/conu/blob/master/requirements.in

**Comment by jscotka** [comment]
so it means that we should remove this ``requirements.sh`` file, or make it read these ``requirements.in`` file, because it is not up to date.

**Comment by jpopelka** [comment]
Sorry to confuse you. [requirements.in](https://github.com/user-cont/conu/blob/master/requirements.in) says what python packages (from PyPI) this project needs, while [requirements.sh](https://github.com/user-cont/conu/blob/master/requirements.sh) says what RPMs we want to have installed.

This is how it works in [Dockerfile](https://github.com/user-cont/conu/blob/master/Dockerfile):
1. run [requirements.sh](https://github.com/user-cont/conu/blob/master/requirements.sh) to install all RPMs
2. run `pip install .` which installs all python packages from [requirements.in](https://github.com/user-cont/conu/blob/master/requirements.in). (Actually from [requirements.txt](https://github.com/user-cont/conu/blob/master/requirements.txt) which is generated from requirements.in)

So maybe the [Vagrantfile](https://github.com/user-cont/conu/blob/master/Vagrantfile) needs to run `sudo make install` instead of just `sudo ./requirements.sh` ? But if it wants to run the tests then it also has to first run `sudo make install-test-requirements`.

**Comment by jscotka** [comment]
we can close it.

**Pull request closed without merging**
