### PR TITLE
WIP: CI testing

### PR DESCRIPTION
**Pull request by jpopelka**
do not merge

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/DKBS](https://da.gd/DKBS)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/znN5](https://da.gd/znN5)__
* Comment: __See details for logs__

**Comment by jpopelka** [comment]
[test]

**Comment by jpopelka** [comment]
[test]

**Pull request closed without merging**
